name       : python-pyaes
version    : 1.6.0
release    : 1
source     :
    - https://pypi.python.org/packages/63/31/6768a72cdca5dbd299ae798b690801e6c9c2f018332eec3c5fca79370dba/pyaes-1.6.0.tar.gz : 9cd5a54d914b1eebfb14fcb490315214b6a0304d9f1bb47e90d1d8e0b15ce92e
license    : MIT
component  : programming.python
summary    : Pure-Python Implementation of the AES block-cipher and common modes of operation
description: |
    Pure-Python Implementation of the AES block-cipher and common modes of operation
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
