name       : python-pyaes
version    : 1.6.1
release    : 6
source     :
    - https://pypi.python.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz : 02c1b1405c38d3c370b085fb952dd8bea3fadcee6411ad99f312cc129c536d8f
license    : MIT
component  : programming.python
summary    : Pure-Python Implementation of the AES block-cipher and common modes of operation
description: |
    Pure-Python Implementation of the AES block-cipher and common modes of operation
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
